---
- hosts: ubuntu
  vars:
    teams: 
    - india
    - england
    - australia
    - pakistan]
  tasks:
  - name: print team names
    debug:
      msg: "{{ item }}"
    with_items:
    - "{{ teams }}"
